Repository avocado-framework/avocado, pull requests merged in 2020-11, with the labels that each got.

#4287 Nrunner support to timeout class attribute
  avocado/core/nrunner_avocado_instrumented.py
Labels: nrunner

#4304 Show test logs depending on status [v2]
  avocado/plugins/testlogs.py
  docs/source/guides/user/chapters/plugins.rst
  selftests/functional/test_logs.py
  setup.py
Labels: enhancement

#4288 Yaml to mux documentation fix
  docs/source/plugins/optional/varianter_yaml_to_mux.rst
Labels: documentation

#4325 Settings, variables swap
  avocado/core/settings.py
Labels: refactoring

#4327 Makefile AVOCADO_DIRNAME fix
  Makefile
Labels: bug
