Repository avocado-framework/avocado, pull requests merged in 2020-10, with the labels that each got.

#4256 Doc warnings fix
  docs/source/guides/contributor/chapters/runners.rst
  docs/source/guides/writer/chapters/parameters.rst
Labels: documentation

#4259 nrunner: fix location and name of runner modules
  avocado/core/nrunner.py
Labels: bug, nrunner

#4277 status_server: split status_server_uri logic
  avocado/plugins/runner_nrunner.py
Labels: enhancement

#4278 Fixes external runner when using the JobAPI
  avocado/core/loader.py
Labels: bug

#4276 backport #4239: new family to utils.cpu
  avocado/utils/cpu.py
Labels: bug
