Repository avocado-framework/avocado, pull requests merged in 2020-08, with the labels that each got.

#4043 HTML Plugin: adapt to job status when job has an empty test suite
  optional_plugins/html/avocado_result_html/__init__.py
Labels: bug

#4044 Simple (executable) Tests: provide a more human friendly message on f…
  avocado/core/test.py
Labels: enhancement, low-hanging-fruit

#4045 Fix example Jobs and add most as selftests
  avocado/plugins/runner_nrunner.py
  examples/jobs/passjob_with_test.py
  selftests/jobs/example_nrunner
  selftests/jobs/example_passjob
  selftests/jobs/example_passjob_cit_varianter
  selftests/jobs/example_passjob_html
  selftests/jobs/example_sleepjob_dict_varianter
  selftests/jobs/example_sleepjob_json_varianter
Labels: bug

#4050 Warning of loader and external runner incompatibility [v4]
  avocado/core/loader.py
  docs/source/guides/user/chapters/introduction.rst
  docs/source/guides/user/chapters/loaders.rst
  selftests/functional/test_loader.py
Labels: bug

#4053 selftests/functional/test_job_timeout.py: do not assume tests will run
  selftests/functional/test_job_timeout.py
Labels: bug

#4056 Fix "avocado list" and "avocado nlist" filtering by tags support
  avocado/core/tags.py
  avocado/plugins/list.py
  avocado/plugins/nlist.py
  selftests/functional/test_list.py
  selftests/functional/test_resolver.py
Labels: bug

#4057 [Bug fix] `core.show` is not respected [v2]
  avocado/core/job.py
  avocado/core/output.py
  selftests/functional/test_output.py
Labels: bug

#4063 future.settings: improved docstring on default value
  avocado/core/future/settings.py
Labels: documentation

#4055 Adding support to multiple test_suites (job.test_suites) - Experimental
  avocado/core/job.py
  avocado/core/jobdata.py
  avocado/core/suite.py
  avocado/core/utils.py
  avocado/core/varianter.py
  avocado/plugins/assets.py
  avocado/plugins/diff.py
  avocado/plugins/run.py
  avocado/plugins/runner.py
  avocado/plugins/runner_nrunner.py
  examples/jobs/nrunner.py
  examples/jobs/passjob.py
  examples/jobs/passjob_cit_varianter.py
  examples/jobs/passjob_custom.py
  examples/jobs/passjob_html.py
  examples/jobs/sleepjob_dict_varianter.py
  examples/jobs/sleepjob_json_varianter.py
  optional_plugins/varianter_yaml_to_mux/tests/test_functional.py
  selftests/functional/test_job_api_features.py
  selftests/functional/test_output.py
  selftests/jobs/nrunner_interface
  selftests/jobs/pass
  selftests/unit/test_job.py
  selftests/unit/test_suite.py
Labels: enhancement

#4080 docs: small fixes on documentation
  docs/source/guides/contributor/chapters/plugins.rst
Labels: documentation

#4078 [Bug fix] Result events plugins errors
  avocado/core/job.py
Labels: bug

#4090 Vmimage automatic documentation [v2]
  .gitignore
  docs/source/conf.py
  docs/source/guides/writer/libs/vmimage.rst
Labels: documentation

#4091 future.settings: fix custom configs after plugins load too
  avocado/__init__.py
Labels: bug

#4129 N(ext) Runner + Job: prep work [v2]
  avocado/core/nrunner.py
  avocado/core/plugin_interfaces.py
  avocado/core/requirements/__init__.py
  avocado/core/requirements/cache/__init__.py
  avocado/core/requirements/cache/backends/__init__.py
  avocado/core/requirements/cache/backends/sqlite.py
  avocado/core/spawners/mock.py
  avocado/core/status/repo.py
  avocado/core/status/server.py
  avocado/core/task/__init__.py
  avocado/core/task/runtime.py
  avocado/core/task/statemachine.py
  avocado/core/test_id.py
  avocado/plugins/nrun.py
  avocado/plugins/runner_nrunner.py
  avocado/plugins/spawners/podman.py
  avocado/plugins/spawners/process.py
  examples/tests/passtest_explicit_requirement.py
  selftests/functional/test_requirements_cache.py
  selftests/functional/test_task_statemachine.py
  selftests/unit/test_spawner.py
  selftests/unit/test_status_repo.py
  selftests/unit/test_task_runtime.py
  setup.py
Labels: nrun2run

#4143 Misc Job and N(ext) Runner (and other) fixes [v2]
  avocado/core/nrunner_avocado_instrumented.py
  avocado/core/status/repo.py
  avocado/core/task/statemachine.py
  avocado/plugins/run.py
  examples/jobs/passjob.py
  examples/jobs/passjob_custom.py
  optional_plugins/robot/avocado_robot/runner.py
  selftests/lint.sh
  selftests/unit/test_status_repo.py
Labels: nrun2run

#4145 N(ext) Runner: Job integration
  Makefile
  avocado/core/nrunner.py
  avocado/core/status/repo.py
  avocado/core/utils.py
  avocado/plugins/human.py
  avocado/plugins/runner_nrunner.py
  examples/jobs/nrunner.py
  selftests/unit/test_status_repo.py
  setup.py
Labels: nrun2run

#4147 nrunner: remove its experimental status
  avocado/core/loader.py
  avocado/core/nrunner.py
  avocado/core/nrunner_avocado_instrumented.py
  avocado/core/nrunner_tap.py
  avocado/core/status_server.py
  avocado/core/utils.py
  avocado/plugins/jobs.py
  avocado/plugins/nrun.py
  avocado/plugins/runner_nrunner.py
  docs/source/future/index.rst
  docs/source/future/plugins/cli.cmd.nrun.rst
  docs/source/guides/contributor/chapters/runners.rst
  docs/source/guides/contributor/index.rst
  docs/source/guides/user/chapters/advanced.rst
  docs/source/index.rst
  optional_plugins/robot/avocado_robot/runner.py
  selftests/pre_release/jobs/timesensitive.py
  setup.py
Labels: nrun2run

#4152 nrunner: restore collection of tasks output
  avocado/plugins/runner_nrunner.py
Labels: nrun2run
