Repository avocado-framework/avocado, pull requests merged in 2020-04, with the labels that each got.

#3677 future/settings: Migrate loader_yaml optional plugin to use the new API
  optional_plugins/loader_yaml/avocado_loader_yaml/__init__.py
Labels: optional plugins / utils / contrib, refactoring

#3698 Misc Asset: fix hash creation for the asset location URI
  avocado/plugins/assets.py
  avocado/utils/asset.py
  selftests/functional/test_plugin_assets.py
  selftests/functional/test_utils_asset.py
Labels: comment-on-sprint-review

#3706 nrunner: remove unnecessary method
  avocado/plugins/nrun.py
Labels: refactoring

#3744 nrunner: small fix on podman spawner
  avocado/core/spawners/podman.py
Labels: bug
