Repository avocado-framework/avocado, pull requests merged in 2020-03, with the labels that each got.

#3624 utils/cloudinit: documentation improvements
  avocado/utils/cloudinit.py
Labels: documentation

#3640 utils/network: Big refactoring on network library to improve consistency [v3]
  avocado/utils/configure_network.py
  avocado/utils/gdb.py
  avocado/utils/network/__init__.py
  avocado/utils/network/common.py
  avocado/utils/network/exceptions.py
  avocado/utils/network/hosts.py
  avocado/utils/network/interfaces.py
  avocado/utils/network/ports.py
  selftests/unit/test_utils_network.py
Labels: refactoring

#3645 fixes CVE-2019-18874
  requirements-selftests.txt
Labels: security

#3647 Utils service doc improvements
  avocado/utils/service.py
Labels: documentation

#3662 utils/ssh: Add ignore_status parameter to cmd()
  avocado/utils/ssh.py
Labels: enhancement

#3675 utils/network: fixed get_interface on different iproute output
  avocado/utils/network/interfaces.py
Labels: bug

#3676 future/settings: Migrate html optional plugin to use the new API
  optional_plugins/html/avocado_result_html/__init__.py
Labels: optional plugins / utils / contrib, refactoring
