Repository avocado-framework/avocado, pull requests merged in 2020-12, with the labels that each got.

#4310 blueprints: Adding a BP000 - v2
  docs/source/blueprints/BP000.rst
Labels: blueprints, discussion, documentation

#4340 moving pre/post hooks to job module
  avocado/core/job.py
  avocado/plugins/run.py
Labels: bug

#4349 Restore loader extra listing
  avocado/core/loader.py
  avocado/plugins/list.py
Labels: bug

#4351 [nrunner]Multiple suites
  avocado/plugins/runner_nrunner.py
Labels: bug

#4350 utils.ssh: adding a cleanup master method and a property
  avocado/utils/ssh.py
Labels: enhancement

#4361 Loader listing fix
  avocado/plugins/list.py
Labels: bug

#4360 Status Server compatibility with python 3.6
  avocado/core/status/server.py
Labels: bug
