Repository avocado-framework/avocado, pull requests merged in 2020-06, with the labels that each got.

#3869 selftests/unit/test_job.py: fixes for using the nrunner plugin
  selftests/unit/test_job.py
Labels: nrun2run

#3871 Nrunner: fix Test IDs [v2]
  avocado/core/job.py
  avocado/core/test.py
  avocado/core/test_id.py
  avocado/plugins/nrun.py
  avocado/plugins/runner.py
  avocado/plugins/runner_nrunner.py
  selftests/unit/test_loader.py
  selftests/unit/test_test.py
  selftests/unit/test_test_id.py
Labels: nrun2run

#3887 avocado.utils.wait: use monotonic time
  avocado/utils/wait.py
Labels: enhancement

#3883 codeclimate: enable codecoverage
  .travis.yml
  requirements-selftests.txt
  selftests/run_coverage
Labels: enhancement

#3893 Drop old mentions
  avocado/etc/avocado/avocado.conf
  docs/Makefile
Labels: low-hanging-fruit

#3894 Software Manager: refactor splitting into smaller modules
  avocado/utils/software_manager.py
  avocado/utils/software_manager/__init__.py
  avocado/utils/software_manager/backends/__init__.py
  avocado/utils/software_manager/backends/apt.py
  avocado/utils/software_manager/backends/base.py
  avocado/utils/software_manager/backends/dnf.py
  avocado/utils/software_manager/backends/dpkg.py
  avocado/utils/software_manager/backends/rpm.py
  avocado/utils/software_manager/backends/yum.py
  avocado/utils/software_manager/backends/zypper.py
  avocado/utils/software_manager/distro_packages.py
  avocado/utils/software_manager/inspector.py
  avocado/utils/software_manager/main.py
  avocado/utils/software_manager/manager.py
  setup.py
Labels: refactoring

#3896 avocado/core/app.py: refactor splitting init method
  avocado/core/app.py
Labels: refactoring

#3912 Job API: misc refactors, cleanups and improvements
  avocado/core/exceptions.py
  avocado/core/job.py
  avocado/core/jobdata.py
  optional_plugins/html/avocado_result_html/__init__.py
  selftests/unit/test_job.py
Labels: nrun2run, refactoring, test runner and core APIs

#3915 Selftests: refactor skip condition for existing file
  optional_plugins/loader_yaml/tests/test_yaml_loader.py
  selftests/__init__.py
  selftests/functional/test_nrunner.py
  selftests/unit/test_nrunner.py
  selftests/unit/test_utils_process.py
Labels: refactoring

#3917 codeclimate: enable bandit plugin
  .codeclimate.yml
Labels: experiments

#3924 Optimize sysinfo by not logging duplicates in post
  avocado/core/sysinfo.py
  avocado/etc/avocado/avocado.conf
  avocado/plugins/sysinfo.py
Labels: enhancement

#3938 Fix issue in linux_modules
  avocado/utils/linux_modules.py
Labels: bug

#3946 Docs: show configuration reference on builds done at readthedocs.io
  avocado/plugins/config.py
  docs/Makefile
  docs/source/conf.py
Labels: documentation
