Repository avocado-framework/avocado, pull requests merged in 2021-06, with the labels that each got.

#4637 nrunner: prep work for variants support
  avocado/plugins/runner.py
  avocado/plugins/runner_nrunner.py
Labels: nrunner

#4639 requirements-selftests.txt: update versions
  requirements-selftests.txt
Labels: dependencies

#4629 Proper nrunner message saving [v2]
  avocado/core/messages.py
  avocado/core/runners/avocado_instrumented.py
  avocado/core/runners/requirement_package.py
  docs/source/guides/contributor/chapters/runners.rst
  selftests/unit/test_runner_requirement_package.py
Labels: nrunner

#4651 Safeloader module split [v2]
  avocado/core/safeloader/__init__.py
  avocado/core/safeloader/core.py
  avocado/core/safeloader/docstring.py
  avocado/core/safeloader/module.py
  docs/source/guides/writer/chapters/writing.rst
  selftests/safeloader.sh
  selftests/unit/test_safeloader.py
  selftests/unit/test_safeloader_core.py
  selftests/unit/test_safeloader_docstring.py
  selftests/unit/test_safeloader_module.py
Labels: refactoring

#4658 docs/contributor's guide: update packages required (enchant)
  docs/source/guides/contributor/chapters/environment.rst
Labels: documentation

#4657 User guide minor update
  docs/source/guides/user/chapters/advanced.rst
  docs/source/guides/user/chapters/assets.rst
  docs/source/guides/user/chapters/concepts.rst
  docs/source/guides/user/chapters/configuring.rst
  docs/source/guides/user/chapters/datadirs.rst
  docs/source/guides/user/chapters/installing.rst
  docs/source/guides/user/chapters/introduction.rst
  docs/source/guides/user/chapters/loaders.rst
  docs/source/guides/user/chapters/logging.rst
  docs/source/guides/user/chapters/operations.rst
  docs/source/guides/user/chapters/plugins.rst
  docs/source/guides/user/chapters/requirements.rst
  docs/source/guides/user/chapters/results.rst
  docs/source/guides/user/chapters/tags.rst
Labels: documentation

#4659 Messages documentation fix
  docs/source/guides/contributor/chapters/runners.rst
Labels: documentation

#4670 Docs: remove warning about environment variables from version 62.0
  docs/source/guides/writer/chapters/writing.rst
Labels: documentation

#4671 Safeloader: utility splits
  avocado/core/safeloader/core.py
Labels: refactoring

#4681 Nrunner File message
  avocado/core/messages.py
  docs/source/guides/contributor/chapters/runners.rst
Labels: nrunner

#4689 Setup: cosmetic change on clean and Python 3.9 support
  setup.py
Labels: low-hanging-fruit

#4704 Docs: keep /home references agnostic to specific user
  contrib/scripts/docs-change-home.sh
  docs/source/blueprints/BP003.rst
  docs/source/guides/user/chapters/introduction.rst
  docs/source/guides/writer/chapters/logging.rst
  docs/source/guides/writer/chapters/subclassing.rst
  docs/source/guides/writer/chapters/writing.rst
  docs/source/releases/0_27_1.rst
  man/avocado.rst
Labels: documentation

#4718 Safeloader: support compound, non-relative imports [v2]
  avocado/core/safeloader/core.py
  avocado/core/safeloader/imported.py
  avocado/core/safeloader/module.py
  selftests/.data/safeloader/data/imports.py
  selftests/functional/test_resolver.py
  selftests/safeloader.sh
  selftests/unit/test_loader.py
  selftests/unit/test_safeloader_core.py
  selftests/unit/test_safeloader_imported.py
  spell.ignore
Labels: bug

#4729 Whiteboard results fix
  avocado/core/messages.py
Labels: bug, nrunner

#4733 docs: update known projects using Avocado
  docs/source/misc/index.rst
Labels: documentation

#4736 docs: add POK to the list of known projects using Avocado
  docs/source/misc/index.rst
Labels: documentation

#4699 Nrunner helper methods for sending messages [v2]
  avocado/core/runners/avocado_instrumented.py
  avocado/core/runners/requirement_package.py
  avocado/core/runners/tap.py
  avocado/core/runners/utils/__init__.py
  avocado/core/runners/utils/messages.py
  docs/source/guides/contributor/chapters/runners.rst
  examples/nrunner/runners/avocado-runner-foo
  examples/plugins/tests/magic/avocado_magic/runner.py
  optional_plugins/golang/avocado_golang/runner.py
  optional_plugins/robot/avocado_robot/runner.py
Labels: nrunner
