Repository avocado-framework/avocado, pull requests merged in 2021-08, with the labels that each got.

#4783 [utils] distro.py: enable util to detect distro of a remote machine
  avocado/utils/distro.py
Labels: enhancement

#4825 Safeloader test: support checking a single file
  selftests/safeloader.sh
Labels: low-hanging-fruit

#4871 Podman spawner: default to using image matching the host OS
  avocado/plugins/spawners/podman.py
Labels: enhancement, nrunner

#4874 nrunner: properly support UNIX domain sockets
  avocado/core/nrunner.py
  avocado/core/status/server.py
  examples/jobs/nrunner_unix_status_server.py
  selftests/jobs/example_nrunner_unix_status_server
Labels: nrunner

#4842 Sysinfo utility
  avocado/core/sysinfo.py
  avocado/utils/sysinfo.py
  selftests/unit/test_sysinfo.py
Labels: refactoring, nrunner

#4872 nrunner: bind tasks to their rightful jobs [v2]
  avocado/core/messages.py
  avocado/core/nrunner.py
  avocado/core/status/repo.py
  avocado/plugins/runner_nrunner.py
  selftests/functional/test_output.py
  selftests/unit/test_status_repo.py
Labels: nrunner

#4881 Config for every runnable
  avocado/core/suite.py
Labels: bug, nrunner

#4882 nrunner: abort job early if missing runners
  avocado/plugins/runner_nrunner.py
Labels: nrunner

#4885 nrunner: introduce status server auto mode [v2]
  avocado/plugins/runner_nrunner.py
  avocado/plugins/spawners/podman.py
  examples/jobs/nrunner.py
  examples/jobs/nrunner_unix_status_server.py
  selftests/check.py
  selftests/functional/plugin/test_jsonresult.py
  selftests/functional/plugin/test_logs.py
  selftests/functional/test_basic.py
  selftests/functional/test_nrunner.py
  selftests/functional/test_output.py
  selftests/functional/test_task_timeout.py
Labels: nrunner

#4876 Default log file for nrunner based tests [v2]
  avocado/core/messages.py
Labels: bug, nrunner

#4878 Sysinfo nrunner [v3]
  avocado/core/runners/sysinfo.py
  examples/nrunner/recipes/runnables/sysinfo.json
  python-avocado.spec
  selftests/unit/test_runner_sysinfo.py
  setup.py
Labels: nrunner
