Repository avocado-framework/avocado, pull requests merged in 2021-04, with the labels that each got.

#4501 TAP: unify implementation with exec based runners
  avocado/core/nrunner.py
  avocado/core/runners/tap.py
Labels: bug, nrunner

#4504 Selftests: refactor to the skip tests
  selftests/functional/test_skiptests.py
Labels: refactoring

#4505 Decorators: fix issue with conditional skips and None
  avocado/core/decorators.py
  selftests/functional/test_skiptests.py
Labels: bug

#4509 Sysinfo: support configuration files installed system wide [v2]
  avocado/core/utils.py
  avocado/plugins/sysinfo.py
Labels: LTS fix, bug

#4512 Nrunner comunication [v2]
  avocado/core/job.py
  avocado/core/messages.py
  avocado/core/nrunner.py
  avocado/core/runners/avocado_instrumented.py
  avocado/core/status/repo.py
  avocado/plugins/runner_nrunner.py
  docs/source/guides/contributor/chapters/runners.rst
  examples/nrunner/runners/avocado-runner-foo
  selftests/unit/test_status_repo.py
  spell.ignore
Labels: nrunner

#4517 Nrunner: restore stdout/stderr log files [v2]
  avocado/core/messages.py
  avocado/core/nrunner.py
  avocado/core/runners/tap.py
  avocado/plugins/runner_nrunner.py
  selftests/functional/test_nrunner.py
  selftests/unit/test_nrunner.py
Labels: bug, nrunner

#4521 Assets Plugin: return meaningful exit codes
  avocado/plugins/assets.py
  selftests/functional/plugin/test_assets.py
Labels: bug

#4528 Skip Decorators: fix issues when setUp or the test function would/would not be run
  avocado/core/decorators.py
  avocado/core/test.py
  selftests/functional/test_skiptests.py
Labels: bug

#4530 Log information when running tests
  avocado/plugins/testlogs.py
  selftests/functional/plugin/test_logs.py
  setup.py
Labels: bug

#4539 assets: warn the user when a hash is not provided
  avocado/utils/asset.py
Labels: customer:QEMU

#4536 Instrumented nrunner error handling
  avocado/core/runners/avocado_instrumented.py
Labels: nrunner

#4555 Task identifier as TestID [v3]
  avocado/core/messages.py
  avocado/core/test_id.py
Labels: bug
