Repository avocado-framework/avocado, pull requests merged in 2021-05, with the labels that each got.

#4576 core.suite: small fix on getting config
  avocado/core/suite.py
Labels: bug

#4582 Run: allow references from config
  avocado/core/settings.py
  avocado/core/suite.py
  avocado/plugins/run.py
  selftests/functional/test_basic.py
  selftests/unit/test_settings.py
Labels: customer:QEMU, enhancement

#4586 isort: fixing import order for avocado/plugins/list.py
  avocado/plugins/list.py
Labels: bug

#4597 HTML plugin: do not pin to Python 3.5 compatible requirements
  optional_plugins/html/setup.py
Labels: bug

#4602 Refresh avocado man-page (v2)
  man/avocado.rst
Labels: documentation

#4605 Empty reference in resolver [v3]
  avocado/core/plugin_interfaces.py
  avocado/core/resolver.py
  docs/source/guides/contributor/chapters/plugins.rst
  examples/plugins/tests/magic/avocado_magic/resolver.py
  examples/plugins/tests/magic/setup.py
Labels: nrunner

#4614 rpm: Get string type of output of installed version to be compared with
  avocado/utils/software_manager/backends/rpm.py
Labels: LTS fix

#4622 nrunner: set the occurred test status to the suite summary [v2]
  avocado/core/job.py
  avocado/core/status/repo.py
  avocado/plugins/runner_nrunner.py
Labels: bug, nrunner

#4621 update packages required for development (v2)
  Makefile
  docs/source/guides/contributor/chapters/environment.rst
  requirements-selftests.txt
  setup.py
Labels: documentation
