Repository avocado-framework/avocado, pull requests merged in 2021-11, with the labels that each got.

#5079 Misc fix / refactor
  avocado/core/jobdata.py
  avocado/plugins/dict_variants.py
Labels: bug

#5080 nrunner interface: add checks and fixes for bare "runnable-run"
  avocado/core/nrunner.py
  optional_plugins/golang/avocado_golang/runner.py
  optional_plugins/robot/avocado_robot/runner.py
  selftests/check.py
  selftests/functional/test_nrunner_interface.py
  selftests/jobs/nrunner_interface
Labels: bug

#5086 Nrunner: fix missing default when using the API [v2]
  avocado/core/__init__.py
  avocado/core/runners/avocado_instrumented.py
  avocado/core/suite.py
  avocado/plugins/run.py
  selftests/check.py
  selftests/unit/test_job.py
Labels: bug

#5085 `--store-logging-stream` fix for the nrunner
  avocado/core/job.py
  avocado/core/runners/utils/messages.py
  docs/source/guides/writer/chapters/logging.rst
  selftests/functional/test_basic.py
Labels: bug

#5056 Option `--show` fix
  avocado/core/messages.py
  avocado/core/runners/utils/messages.py
  docs/source/guides/writer/chapters/logging.rst
  selftests/functional/test_basic.py
Labels: bug

#5090 Avocado jobs: allow nrunner jobs from eggs
  .cirrus.yml
  avocado/core/nrunner.py
Labels: bug

#5093 Remove all manual assigments of nrunner [v2]
  avocado/core/suite.py
  contrib/testsuites/run-kvm-unit-test.sh
  docs/source/guides/user/chapters/introduction.rst
  docs/source/guides/user/chapters/results.rst
  examples/jobs/custom_exec_test.py
  examples/jobs/multiple_suites_from_config.py
  examples/jobs/nrunner.py
  examples/jobs/passjob_custom.py
  examples/jobs/unix_status_server.py
  selftests/check.py
  selftests/functional/test_nrunner.py
  selftests/functional/test_output.py
  selftests/jobs/example_nrunner
  selftests/jobs/example_nrunner_unix_status_server
  selftests/jobs/example_unix_status_server
  selftests/pre_release/jobs/pre_release.py
  selftests/unit/test_job.py
Labels: bug

#5100 utils/network/interfaces.py: Update error message
  avocado/utils/network/interfaces.py
Labels: bug

#5106 optional_plugins/resultsdb: set versioned requires
  optional_plugins/resultsdb/setup.py
Labels: bug

#5109 check.py: fix --list-features
  selftests/check.py
Labels: bug

#5122 GH: new bug reports will receive the 'triage' tag
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: enhancement, experiments

#5124 RPM: do not build resultsdb plugin on Fedora 36 (rawhide) or later
  python-avocado.spec
Labels: bug

#5114 utils.vmimage issues
  avocado/utils/vmimage.py
  selftests/pre_release/jobs/pre_release.py
  selftests/pre_release/tests/vmimage.py.data/variants.yml
  selftests/unit/utils/test_vmimage.py
Labels: bug

#5123 Convert test parameters to variants in tasks
  avocado/core/messages.py
  avocado/core/nrunner.py
  avocado/core/runners/avocado_instrumented.py
  avocado/plugins/runner_nrunner.py
Labels: bug

#5130 release.yml: updates for setting up variables and move readthedocs step
  .github/workflows/release.yml
  Makefile.gh
Labels: bug

#5142 ci.yml: run static-checks only once
  .github/workflows/ci.yml
Labels: enhancement

#5161 docs/guides/writer: update vmimage
  docs/source/guides/writer/libs/vmimage.rst
Labels: documentation
