Repository avocado-framework/avocado, pull requests merged in 2021-07, with the labels that each got.

#4757 File message fix
  avocado/core/runners/utils/messages.py
Labels: bug, nrunner

#4769 Setup: add support for excluding optional plugins on develop
  .cirrus.yml
  .github/workflows/ci.yml
  python-avocado.spec
  setup.py
Labels: bug

#4740 Task status_server_uri
  avocado/core/nrunner.py
  avocado/core/suite.py
  avocado/plugins/runner_nrunner.py
Labels: nrunner

#4746 Config variable for resolvers [v2]
  avocado/core/plugin_interfaces.py
  avocado/core/resolver.py
  avocado/core/suite.py
  avocado/plugins/resolvers.py
Labels: nrunner

#4781 logfile value in results.json [v2]
  avocado/core/messages.py
  selftests/functional/plugin/test_jsonresult.py
Labels: bug, nrunner

#4764 safeloader: do not choke on classes with generic parents
  avocado/core/safeloader/core.py
  selftests/unit/test_safeloader_core.py
Labels: bug

#4776 Nrunner functional tests fix
  selftests/functional/plugin/test_logs.py
  selftests/functional/test_basic.py
Labels: bug

#4792 Safeloader: respect disable on all Python tests and ignore teststmpdir
  avocado/core/safeloader/core.py
  avocado/core/test.py
  selftests/unit/test_loader.py
Labels: bug

#4780 Instrumented tests with fail reason [v2]
  avocado/core/runners/avocado_instrumented.py
  selftests/functional/plugin/test_jsonresult.py
Labels: bug, nrunner

#4807 Resolver and Discoverer plugins initialization fix
  avocado/core/plugin_interfaces.py
  avocado/core/resolver.py
Labels: bug

#4809 Software manager: fix extraction of deb packages
  avocado/utils/ar.py
  avocado/utils/software_manager/backends/dpkg.py
  avocado/utils/software_manager/backends/rpm.py
  selftests/.data/guaca.a
  selftests/functional/test_software_manager.py
  selftests/unit/utils/test_ar.py
  selftests/unit/utils/test_software_manager.py
Labels: bug

#4811 Sysinfo: cleanups and preps for nrunner
  avocado/core/sysinfo.py
Labels: nrunner
