Repository avocado-framework/avocado, pull requests merged in 2021-01, with the labels that each got.

#4373 Inspekt-style fix
  avocado/core/loader.py
  avocado/core/output.py
  avocado/core/status/repo.py
  avocado/core/test.py
  avocado/plugins/dict_variants.py
  avocado/plugins/runner_nrunner.py
  avocado/utils/kernel.py
  docs/source/conf.py
  selftests/check.py
  selftests/functional/test_basic.py
  selftests/functional/test_loader.py
  selftests/functional/test_output.py
  selftests/functional/test_plugin_jobscripts.py
  selftests/inspekt-style.sh
  selftests/unit/test_utils_network.py
  selftests/unit/test_xunit.py
Labels: bug

#4330 nrunner: introduce 'task.timeout.running' config option as timeout and small fix
  avocado/core/task/statemachine.py
  avocado/plugins/runner_nrunner.py
  selftests/functional/test_task_timeout.py
Labels: enhancement

#4383 Makefile: migrate clean target to setup.py and cleanups
  Makefile
  docs/source/guides/contributor/chapters/environment.rst
  setup.py
Labels: enhancement, experiments, refactoring
