Repository avocado-framework/avocado, pull requests merged in 2022-04, with the labels that each got.

#5306 job config rewrites the suite config in job API
  avocado/core/suite.py
Labels: bug

#5315 Remove the outdated documentation
  docs/source/guides/user/chapters/logging.rst
Labels: documentation

#5326 Runner: only pass configuration that is potentially used [v3]
  avocado/core/nrunner/__main__.py
  avocado/core/nrunner/app.py
  avocado/core/nrunner/runnable.py
  avocado/core/nrunner/runner.py
  avocado/core/runners/asset.py
  avocado/core/runners/avocado_instrumented.py
  avocado/core/runners/exec_test.py
  avocado/core/runners/package.py
  avocado/core/runners/sysinfo.py
  avocado/core/suite.py
  avocado/plugins/runner_nrunner.py
  docs/source/guides/contributor/chapters/plugins.rst
  examples/nrunner/recipes/runnables/asset.json
  examples/nrunner/recipes/runnables/package_check_foo.json
  selftests/functional/test_nrunner_interface.py
  selftests/functional/test_runner_asset.py
  selftests/functional/test_runner_package.py
  selftests/unit/test_runner_asset.py
  selftests/unit/test_runner_package.py
  setup.py
  spell.ignore
Labels: nrunner

#5339 Runner plugins: move to plugins directory [v2]
  avocado/core/nrunner/runnable.py
  avocado/core/runners/utils/__init__.py
  avocado/core/utils/messages.py
  avocado/plugins/runners/__init__.py
  avocado/plugins/runners/asset.py
  avocado/plugins/runners/avocado_instrumented.py
  avocado/plugins/runners/dry_run.py
  avocado/plugins/runners/exec_test.py
  avocado/plugins/runners/noop.py
  avocado/plugins/runners/package.py
  avocado/plugins/runners/python_unittest.py
  avocado/plugins/runners/sysinfo.py
  avocado/plugins/runners/tap.py
  docs/source/guides/contributor/chapters/runners.rst
  examples/nrunner/runners/avocado-runner-foo
  examples/plugins/tests/magic/avocado_magic/runner.py
  optional_plugins/golang/avocado_golang/runner.py
  optional_plugins/robot/avocado_robot/runner.py
  selftests/functional/test_runner_asset.py
  selftests/functional/test_runner_package.py
  selftests/unit/test_nrunner.py
  selftests/unit/test_runner_asset.py
  selftests/unit/test_runner_package.py
  selftests/unit/test_runner_sysinfo.py
  setup.py
Labels: nrunner

#5346 Drop SIMPLE test and other legacy code [v2]
  avocado/core/loader.py
  avocado/core/status/repo.py
  avocado/core/test.py
  avocado/plugins/runners/exec_test.py
  docs/source/guides/contributor/chapters/runners.rst
  docs/source/guides/writer/chapters/writing.rst
  selftests/functional/test_basic.py
  selftests/functional/test_job_timeout.py
  selftests/unit/test_loader.py
  selftests/unit/test_test.py
Labels: legacy

#5362 Drop legacy runner [v2]
  .github/workflows/setup.yml
  avocado/core/job.py
  avocado/core/suite.py
  avocado/plugins/assets.py
  avocado/plugins/human.py
  avocado/plugins/run.py
  avocado/plugins/runner.py
  avocado/plugins/runners/avocado_instrumented.py
  avocado/plugins/wrapper.py
  avocado/utils/process.py
  docs/source/guides/contributor/chapters/runners.rst
  docs/source/guides/user/chapters/advanced.rst
  docs/source/guides/writer/chapters/writing.rst
  examples/tests/vm-cleanup.py
  examples/tests/vm-cleanup.py.data/vm-cleanup.yaml
  examples/wrappers/bind_cpu0.sh
  examples/wrappers/dummy.sh
  examples/wrappers/ltrace.sh
  examples/wrappers/perf.sh
  examples/wrappers/rr.sh
  examples/wrappers/strace.sh
  examples/wrappers/time.sh
  examples/wrappers/valgrind.sh
  python-avocado.spec
  selftests/functional/test_basic.py
  selftests/functional/test_fetch_asset.py
  selftests/functional/test_getdata.py
  selftests/functional/test_interrupt.py
  selftests/functional/test_json_variants.py
  selftests/functional/test_list.py
  selftests/functional/test_output.py
  selftests/functional/test_resolver.py
  selftests/functional/test_streams.py
  selftests/functional/test_wrapper.py
  selftests/unit/test_loader.py
  setup.py
Labels: legacy
