Repository avocado-framework/avocado, pull requests merged in 2022-11, with the labels that each got.

#5505 Python path environment bomb fix
  avocado/core/nrunner/runnable.py
  avocado/plugins/spawners/process.py
Labels: bug

#5508 `Setting a Test Timeout` doc update
  docs/source/guides/writer/chapters/writing.rst
Labels: documentation

#5510 Python 3.11 support
  .github/workflows/ci.yml
  .github/workflows/weekly.yml
  avocado/core/spawners/mock.py
  avocado/plugins/assets.py
  avocado/plugins/beaker_result.py
  avocado/plugins/bystatus.py
  avocado/plugins/diff.py
  avocado/plugins/human.py
  avocado/plugins/journal.py
  avocado/plugins/spawners/podman.py
  avocado/plugins/sysinfo.py
  avocado/plugins/tap.py
  avocado/plugins/testlogs.py
  avocado/plugins/teststmpdir.py
  optional_plugins/resultsdb/avocado_resultsdb/resultsdb.py
  setup.py
Labels: refactoring
