Repository avocado-framework/avocado, pull requests merged in 2022-07, with the labels that each got.

#5419 Fedora version update for vmimage
  selftests/pre_release/tests/vmimage.py.data/variants.yml
Labels: bug

#5425 Test results with warning fix
  avocado/core/test.py
  examples/tests/failtest_with_warning.py
  selftests/functional/test_basic.py
Labels: bug

#5428 Task timeout handling fix
  avocado/core/messages.py
Labels: bug

#5432 82lts: Python311 unittest fail fix
  docs/source/guides/user/chapters/operations.rst
  examples/tests/doublefree.py
  examples/tests/doublefree.py.data/doublefree.c
  examples/tests/doublefree_nasty.py
  examples/tests/doublefree_nasty.py.data/doublefree.c
  examples/tests/doublefree_nasty.py.data/gdb_pre
  examples/tests/doublefree_nasty.py.data/iterations.yaml
  man/avocado.rst
  selftests/functional/test_output.py
  selftests/unit/test_nrunner.py
  spell.ignore
Labels: LTS fix

#5447 `Black` static checks update
  selftests/style.sh
Labels: enhancement
