Repository avocado-framework/avocado, pull requests merged in 2023-11, with the labels that each got.

#5788 Spawner: make terminate_task return success or failure
  avocado/core/__init__.py
  avocado/core/plugin_interfaces.py
  avocado/core/status/repo.py
  avocado/core/task/statemachine.py
  avocado/plugins/spawners/lxc.py
  avocado/plugins/spawners/podman.py
  avocado/plugins/spawners/process.py
  examples/plugins/tests/rogue/avocado_rogue/__init__.py
  examples/plugins/tests/rogue/avocado_rogue/resolver.py
  examples/plugins/tests/rogue/avocado_rogue/runner.py
  examples/plugins/tests/rogue/setup.py
  selftests/functional/plugin/spawners/process.py
  selftests/unit/plugin/spawner.py
Labels: bug

#5774 Bump cryptography to avoid security alerts
  optional_plugins/ansible/setup.py
  requirements-dev.txt
Labels: dependencies

#5803 avocado jobs show: fix retrieval of ERROR
  avocado/plugins/jobs.py
Labels: bug

#5800 external_runner import error fix
  scripts/external_runner.py
Labels: bug

#5805 Process Spawner: protect against races between TERM and KILL
  avocado/plugins/spawners/process.py
Labels: bug

#5811 Python 3.13 enablement
  avocado/core/test.py
Labels: LTS fix

#5787 corrupt resolution result
  .github/workflows/ci.yml
  avocado/core/resolver.py
  avocado/plugins/list.py
  docs/source/guides/contributor/chapters/plugins.rst
  examples/plugins/tests/magic/avocado_magic/resolver.py
  examples/plugins/tests/magic/avocado_magic/runner.py
  selftests/functional/resolver.py
Labels: enhancement

#5812 Fedora CI update from 36 to 38
  .github/workflows/ansible.yml
  .github/workflows/ci.yml
  selftests/functional/serial/requirements.py
Labels: bug

#5804 INTERRUPTED status overwrite fix
  avocado/core/task/statemachine.py
  avocado/core/test.py
  selftests/.data/test_statuses.py
  selftests/functional/statuses.py
Labels: bug
