Repository avocado-framework/avocado, pull requests merged in 2023-06, with the labels that each got.

#5696 Improve message when resolvers don't resolve the reference
  avocado/core/resolver.py
  selftests/functional/basic.py
Labels: enhancement, customer:Passt

#5687 Tags inheritance
  avocado/core/safeloader/core.py
  selftests/unit/safeloader_core.py
  selftests/unit/tags.py
Labels: enhancement, customer:Passt

#5682 Task result in lower case
  avocado/core/task/runtime.py
Labels: bug

#5699 Document standard plugin teststmpdir
  docs/source/guides/writer/chapters/writing.rst
  docs/source/plugins/index.rst
  docs/source/plugins/standard/teststmpdir.rst
Labels: documentation

#5695 signedoff-check.sh false positive fix
  .github/workflows/ci.yml
  selftests/signedoff-check.sh
Labels: bug

#5661 examples/tests/test_env.py: protect against lack of isatty()
  examples/tests/test_env.py
Labels: bug

#5698 Optional plugins: move documentation to plugin themsevels
  docs/source/plugins/index.rst
  docs/source/plugins/optional/golang.rst
  docs/source/plugins/optional/multiplexer.rst
  docs/source/plugins/optional/results.rst
  docs/source/plugins/optional/results/html.rst
  docs/source/plugins/optional/results/index.rst
  docs/source/plugins/optional/results/result_upload.rst
  docs/source/plugins/optional/results/resultsdb.rst
  docs/source/plugins/optional/robot.rst
  docs/source/plugins/optional/varianters/cit.rst
  docs/source/plugins/optional/varianters/index.rst
  docs/source/plugins/optional/varianters/pict.rst
  docs/source/plugins/optional/varianters/yaml_to_mux.rst
  optional_plugins/golang/MANIFEST.in
  optional_plugins/golang/README
  optional_plugins/golang/README.rst
  optional_plugins/golang/setup.py
  optional_plugins/html/MANIFEST.in
  optional_plugins/html/README
  optional_plugins/html/README.rst
  optional_plugins/html/setup.py
  optional_plugins/result_upload/MANIFEST.in
  optional_plugins/result_upload/README
  optional_plugins/result_upload/README.rst
  optional_plugins/result_upload/setup.py
  optional_plugins/resultsdb/MANIFEST.in
  optional_plugins/resultsdb/README
  optional_plugins/resultsdb/README.rst
  optional_plugins/resultsdb/setup.py
  optional_plugins/robot/MANIFEST.in
  optional_plugins/robot/README
  optional_plugins/robot/README.rst
  optional_plugins/robot/setup.py
  optional_plugins/varianter_cit/MANIFEST.in
  optional_plugins/varianter_cit/README
  optional_plugins/varianter_cit/README.rst
  optional_plugins/varianter_cit/setup.py
  optional_plugins/varianter_pict/README
  optional_plugins/varianter_pict/README.rst
  optional_plugins/varianter_pict/setup.py
  optional_plugins/varianter_yaml_to_mux/MANIFEST.in
  optional_plugins/varianter_yaml_to_mux/README
  optional_plugins/varianter_yaml_to_mux/README.rst
  optional_plugins/varianter_yaml_to_mux/setup.py
  setup.py
Labels: documentation

#5665 Avocado logging cleanup [v2]
  avocado/core/__init__.py
  avocado/core/job.py
  avocado/core/messages.py
  avocado/core/output.py
  avocado/core/streams.py
  avocado/core/test.py
  avocado/core/utils/messages.py
  docs/source/guides/user/chapters/introduction.rst
  docs/source/guides/user/chapters/logging.rst
  docs/source/guides/writer/chapters/logging.rst
  examples/tests/external_logging_stream.py
  examples/tests/logging_streams.py
  selftests/functional/basic.py
  selftests/functional/output.py
  selftests/functional/streams.py
Labels: enhancement, refactoring

#5664 Assets plugin: do not assume assigments have ids
  avocado/plugins/assets.py
  selftests/unit/plugin/assets.py
Labels: bug

#5701 DependencyResolver output fix [v2]
  avocado/core/messages.py
  avocado/core/task/runtime.py
  avocado/core/task/statemachine.py
  docs/source/guides/user/chapters/dependencies.rst
  selftests/functional/serial/requirements.py
Labels: bug

#5679 Environment variables for exec tests
  avocado/plugins/runners/exec_test.py
  avocado/plugins/spawners/process.py
  docs/source/guides/writer/chapters/writing.rst
  examples/tests/env_variables.sh
  selftests/functional/plugin/runners/exec_test.py
Labels: bug, customer:Passt

#5705 selftests tmp dir cleanup fix
  Makefile
  selftests/check.py
  selftests/functional/basic.py
  selftests/functional/plugin/runners/exec_test.py
  selftests/functional/serial/requirements.py
Labels: bug

#5706 Task termination fix
  avocado/core/task/statemachine.py
Labels: bug
