Repository avocado-framework/avocado, pull requests merged in 2023-10, with the labels that each got.

#5728 Avocado-instrumented default timeout removal
  avocado/plugins/runners/avocado_instrumented.py
  selftests/functional/plugin/runners/avocado_instrumented.py
Labels: bug

#5763 Doc fixes before LTS - Avocado User’s Guide
  docs/source/guides/contributor/chapters/plugins.rst
  docs/source/guides/contributor/chapters/runners.rst
  docs/source/guides/user/chapters/advanced.rst
  docs/source/guides/user/chapters/configuring.rst
  docs/source/guides/user/chapters/datadirs.rst
  docs/source/guides/user/chapters/dependencies.rst
  docs/source/guides/user/chapters/installing.rst
  docs/source/guides/user/chapters/introduction.rst
  docs/source/guides/user/chapters/operations.rst
  docs/source/guides/user/chapters/plugins.rst
  docs/source/guides/user/chapters/results.rst
  docs/source/guides/user/chapters/tags.rst
  docs/source/guides/writer/chapters/writing.rst
  examples/tests/tags.py
  selftests/functional/list.py
  selftests/unit/tags.py
Labels: documentation

#5773 Whiteboard save removed from Test class
  avocado/core/test.py
  selftests/functional/output.py
  selftests/unit/test.py
Labels: bug

#5758 Doc fixes before LTS - Introduction section
  docs/source/quickstart/index.rst
Labels: documentation

#5775 avocado/utils/ssh.py: add timeout functionality
  avocado/utils/ssh.py
  examples/apis/utils/ssh_timeout.py
Labels: optional plugins / utils / contrib

#5762 Improve Avocado jobs command
  avocado/plugins/jobs.py
Labels: bug

#5778 Twine check for release
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Makefile.gh
  optional_plugins/ansible/setup.py
  optional_plugins/varianter_pict/setup.py
  optional_plugins/varianter_yaml_to_mux/setup.py
Labels: enhancement

#5780 Doc fixes before LTS - Avocado Writers’s Guide
  docs/source/guides/writer/chapters/libs.rst
  docs/source/guides/writer/chapters/logging.rst
  docs/source/guides/writer/chapters/parameters.rst
  docs/source/guides/writer/chapters/writing.rst
  docs/source/guides/writer/libs/gdb.rst
Labels: documentation

#5785 output: support for kitty
  avocado/core/output.py
Labels: low-hanging-fruit

#5783 Podman Improvements
  avocado/plugins/spawners/podman.py
Labels: optional plugins / utils / contrib, bug

#5786 Example plugins for test types: enable them during development mode
  .github/workflows/weekly.yml
  examples/plugins/tests/magic/avocado_magic/resolver.py
  examples/plugins/tests/magic/avocado_magic/runner.py
  examples/plugins/tests/magic/setup.py
  setup.py
Labels: optional plugins / utils / contrib

#5781 'avocado.test.stdout' and 'avocado.test.stderr' streams fix
  avocado/core/utils/messages.py
  selftests/functional/output.py
Labels: bug
