Repository avocado-framework/avocado, pull requests merged in 2023-12, with the labels that each got.

#5825 readthedocs.org: install Avocado instead of devel requirements
  .readthedocs.yaml
Labels: documentation

#5820 Avocado Instrumented Test: introduce a multiplier for the timeout
  avocado/core/test.py
  docs/source/guides/writer/chapters/writing.rst
  examples/tests/timeouttest.py
  selftests/functional/basic.py
Labels: customer:QEMU

#5815 Sphinx warnings and errors fix
  .readthedocs.yaml
  avocado/core/dispatcher.py
  avocado/core/plugin_interfaces.py
  avocado/core/task/runtime.py
  avocado/core/utils/messages.py
  avocado/utils/cpu.py
  avocado/utils/external/gdbmi_parser.py
  avocado/utils/network/interfaces.py
  avocado/utils/pci.py
  avocado/utils/podman.py
  avocado/utils/software_manager/backends/rpm.py
  avocado/utils/software_manager/backends/yum.py
  avocado/utils/software_manager/backends/zypper.py
  docs/source/blueprints/BP003.rst
  docs/source/blueprints/BP005.rst
  docs/source/blueprints/template.rst
  docs/source/conf.py
  docs/source/guides/contributor/chapters/plugins.rst
  docs/source/guides/reference/chapters/runners.rst
  docs/source/guides/writer/chapters/writing.rst
  docs/source/plugins/index.rst
  docs/source/releases/53_0.rst
  docs/source/releases/59_0.rst
  docs/source/releases/61_0.rst
  docs/source/releases/71_0.rst
  docs/source/releases/84_0.rst
  docs/source/releases/95_0.rst
  docs/source/releases/lts/69_0.rst
  docs/source/releases/lts/92_0.rst
Labels: documentation, bug

#5829 HTML results status filter fix
  optional_plugins/html/avocado_result_html/templates/avocado_html.js
Labels: bug

#5822 Selftest refactoring to fix masked tests
  avocado/core/job.py
  avocado/core/utils/messages.py
  docs/source/guides/writer/chapters/writing.rst
  selftests/check.py
  selftests/functional/basic.py
Labels: refactoring

#5831 IRC channel doc removal
  docs/source/guides/contributor/chapters/contact.rst
  docs/source/guides/contributor/chapters/how.rst
Labels: documentation

#5832 Better description of Environment Variables in doc
  docs/source/guides/writer/chapters/writing.rst
Labels: documentation

#5833 Add simplewarning.sh example to doc
  docs/source/guides/writer/chapters/writing.rst
Labels: documentation

#5834 Add CentOS Stream to distro util
  avocado/utils/distro.py
Labels: bug

#5835 Update Amazon Linux distro description
  avocado/utils/distro.py
Labels: bug

#5840 Contributor guide review
  .readthedocs.yaml
  docs/Makefile
  docs/source/.include/helpus.rst
  docs/source/conf.py
  docs/source/guides/contributor/chapters/environment.rst
  docs/source/guides/contributor/chapters/how.rst
  docs/source/guides/contributor/chapters/plugins.rst
  docs/source/guides/contributor/chapters/results.rst
  docs/source/guides/contributor/chapters/rfc.rst
  docs/source/guides/contributor/chapters/styleguides.rst
  docs/source/guides/user/chapters/concepts.rst
  docs/source/quickstart/index.rst
  requirements-doc.txt
Labels: documentation

#5842 Man page updates
  avocado/core/__init__.py
  avocado/core/settings.py
  docs/source/plugins/index.rst
  docs/source/plugins/standard/distro.rst
  man/avocado.rst
Labels: documentation

#5843 Optional plugins review for 103.0 LTS
  optional_plugins/golang/avocado_golang/runner.py
  optional_plugins/html/README.rst
  optional_plugins/varianter_cit/README.rst
  optional_plugins/varianter_pict/README.rst
Labels: documentation, bug
