Repository avocado-framework/avocado, pull requests merged in 2023-07, with the labels that each got.

#5716 Test file import versus system module
  avocado/core/utils/loader.py
Labels: bug

#5727 avocado/core/loader.py: support Python 3.12 by using importlib
  .github/workflows/ci.yml
  avocado/core/loader.py
  optional_plugins/robot/setup.py
Labels: LTS fix

#5731 Dependencies weren't fulfilled fix
  avocado/core/task/statemachine.py
  avocado/core/utils/messages.py
  selftests/functional/serial/requirements.py
Labels: bug

#5739 Improve Contributor's Guide: Drop requirement of PR versions
  docs/source/guides/contributor/chapters/how.rst
Labels: documentation
