Repository avocado-framework/avocado, pull requests merged in 2024-01, with the labels that each got.

#5846 Add a quick guide for setting up the remote spawner
  docs/source/plugins/index.rst
  docs/source/plugins/optional/spawner_remote.rst
  optional_plugins/spawner_remote/README.rst
  optional_plugins/spawner_remote/setup.py
Labels: documentation

#5849 Release notes for LTS version 103.0
  docs/source/releases/index.rst
  docs/source/releases/lts/103_0.rst
Labels: documentation

#5854 Insecure temporary file removal
  optional_plugins/html/tests/html_result.py
  selftests/functional/output.py
Labels: bug, security

#5856 Add CodeQL workflow for GitHub code scanning
  .github/workflows/codeql.yml
Labels: security

#5859 AvocadoConfigParser
  avocado/core/jobdata.py
  avocado/core/settings.py
  selftests/check.py
  selftests/functional/replay.py
  selftests/functional/settings.py
Labels: bug, customer:Passt

#5860 TaskStatusService connection lost fix
  avocado/core/nrunner/task.py
  selftests/check.py
  selftests/functional/nrunner.py
Labels: bug
