Repository avocado-framework/avocado, pull requests merged in 2024-08, with the labels that each got.

#5996 avocado/utils/archive.py: make probe function for zstd public
  avocado/utils/archive.py
  selftests/unit/utils/archive.py
Labels: customer:QEMU

#5943 Mail Job Notification Plugin
  docs/source/plugins/optional/results/index.rst
  docs/source/plugins/optional/results/mail.rst
  examples/plugins/job-pre-post/mail/avocado_job_mail.py
  examples/plugins/job-pre-post/mail/setup.py
  optional_plugins/mail/MANIFEST.in
  optional_plugins/mail/README
  optional_plugins/mail/README.rst
  optional_plugins/mail/VERSION
  optional_plugins/mail/avocado_result_mail/__init__.py
  optional_plugins/mail/avocado_result_mail/result_mail.py
  optional_plugins/mail/setup.py
  python-avocado.spec
  spell.ignore
Labels: enhancement

#5992 Runnable identifier
  avocado/core/nrunner/runnable.py
  avocado/plugins/list.py
  avocado/schemas/runnable-recipe.schema.json
  examples/jobs/custom_exec_test.py
  examples/nrunner/recipes/runnable/exec_test_sleep_3.json
  examples/nrunner/recipes/runnable/identifier.json
  examples/nrunner/recipes/runnables/true_false.json
  selftests/check.py
  selftests/functional/resolver.py
  selftests/unit/runnable.py
Labels: enhancement, customer:Passt

#6000 logging.warn() refactoring for 92lts
  avocado/plugins/legacy/replay.py
  optional_plugins/varianter_yaml_to_mux/setup.py
Labels: bug

#6005 Tap14 update
  avocado/core/tapparser.py
  avocado/plugins/runners/tap.py
  selftests/check.py
  selftests/unit/tap.py
Labels: enhancement, customer:Dovetail

#6006 Runnable and Suite configuration support
  avocado/core/nrunner/runnable.py
  avocado/core/suite.py
  avocado/plugins/sysinfo.py
  examples/nrunner/recipes/runnable/noop_config.json
  selftests/check.py
  selftests/functional/resolver.py
  selftests/unit/runnable.py
  selftests/unit/suite.py
Labels: customer:Passt

#5999 Backwards compatibility for kernel utils module
  avocado/utils/kernel.py
Labels: bug
