Repository avocado-framework/avocado, pull requests merged in 2024-02, with the labels that each got.

#5864 avocado.Test: remove runner queue
  avocado/core/test.py
Labels: legacy

#5866 Update json result attributes to match with job.result.tests
  avocado/plugins/jsonresult.py
  docs/source/guides/user/chapters/introduction.rst
Labels: bug

#5867 Release next.rst
  docs/source/releases/index.rst
  docs/source/releases/next.rst
Labels: documentation
