Repository avocado-framework/avocado, pull requests merged in 2024-11, with the labels that each got.

#6061 VMimage get --debug option
  avocado/plugins/vmimage.py
  avocado/utils/vmimage.py
  selftests/check.py
  selftests/functional/plugin/vmimage.py
Labels: enhancement

#6069 avocado.utils.kernel: fix kernel version parsing
  avocado/utils/kernel.py
  selftests/check.py
  selftests/unit/utils/kernel.py
Labels: optional plugins / utils / contrib, bug

#6073 Test coverage with multiprocessing fix
  .coveragerc
  selftests/run_coverage
Labels: bug
