Repository avocado-framework/avocado, pull requests merged in 2024-06, with the labels that each got.

#5944 Avocado Coverage.py updates
  .coveragerc
  .github/workflows/ci.yml
  avocado/plugins/runners/avocado_instrumented.py
  avocado/plugins/runners/python_unittest.py
  docs/source/guides/writer/chapters/integrating.rst
  requirements-dev.txt
  selftests/run
  selftests/run_coverage
Labels: enhancement, bug

#5955 Hardcoded nrunner removal in TestSuite
  avocado/core/suite.py
Labels: bug

#5956 vmimage fedora provider update
  avocado/utils/vmimage.py
Labels: bug

#5969 PR announcement as env variable
  .github/workflows/pr_announcement.yml
Labels: enhancement

#5971 PyPI upload update revert
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
Labels: refactoring

#5972 Fix for the latest update of pr_announcement CI
  .github/workflows/pr_announcement.yml
Labels: bug

#5977 Runnable: fix job/suite config use and runnable identifier
  avocado/core/nrunner/runnable.py
  avocado/core/suite.py
  avocado/plugins/runner_nrunner.py
  selftests/check.py
  selftests/unit/nrunner.py
  selftests/unit/suite.py
Labels: bug, customer:Passt
