Repository avocado-framework/avocado, pull requests merged in 2024-04, with the labels that each got.

#5887 User Guide: improve section on Avocado's basic concepts
  docs/source/guides/user/chapters/concepts.rst
Labels: documentation

#5886 Release workflow updates
  .github/workflows/release.yml
Labels: refactoring

#5902 Docs stlye checks backport to 92LTS
  .readthedocs.yaml
  avocado/core/runners/utils/messages.py
  avocado/utils/external/gdbmi_parser.py
  docs/source/blueprints/BP003.rst
  docs/source/blueprints/template.rst
  docs/source/conf.py
  docs/source/guides/contributor/chapters/runners.rst
  requirements-doc.txt
Labels: LTS release

#5900 Remove example "doublefree" tests
  docs/source/guides/user/chapters/operations.rst
  examples/tests/doublefree.py
  examples/tests/doublefree.py.data/doublefree.c
  examples/tests/doublefree_nasty.py
  examples/tests/doublefree_nasty.py.data/doublefree.c
  examples/tests/doublefree_nasty.py.data/gdb_pre
  examples/tests/doublefree_nasty.py.data/iterations.yaml
  man/avocado.rst
  selftests/functional/test_output.py
  spell.ignore
Labels: LTS fix

#5897 Runnable recipe: introduce validation and resolver
  MANIFEST.in
  avocado/core/nrunner/runnable.py
  avocado/core/output.py
  avocado/plugins/list.py
  avocado/plugins/resolvers.py
  avocado/schemas/runnable-recipe.schema.json
  docs/source/guides/writer/chapters/recipes.rst
  docs/source/guides/writer/index.rst
  python-avocado.spec
  selftests/check.py
  selftests/functional/resolver.py
  selftests/unit/nrunner_schema.py
  setup.py
Labels: customer:Passt

#5905 Remove duplicities in dependencies
  avocado/core/dependencies/dependency.py
  avocado/core/safeloader/docstring.py
  avocado/plugins/dependency.py
  selftests/check.py
  selftests/functional/serial/requirements.py
  selftests/unit/dependencies_resolver.py
  selftests/unit/safeloader_docstring.py
Labels: bug

#5896 Suite dependency
  avocado/core/extension_manager.py
  avocado/core/job.py
  avocado/plugins/dependency.py
  avocado/plugins/run.py
  docs/source/guides/user/chapters/dependencies.rst
  selftests/check.py
  selftests/functional/serial/requirements.py
  setup.py
Labels: enhancement, customer:Passt

#5901 Extended environment variable control
  avocado/core/__init__.py
  avocado/core/nrunner/runnable.py
  avocado/plugins/runners/exec_test.py
  docs/source/guides/writer/chapters/basics.rst
  docs/source/guides/writer/chapters/writing.rst
  selftests/check.py
  selftests/functional/basic.py
Labels: enhancement, customer:Passt

#5922 Docs: add the isar project as an Avocado user
  docs/source/misc/index.rst
Labels: documentation

#5921 Pre-release job fixes for 92.2
  avocado/utils/vmimage.py
  docs/source/quickstart/index.rst
  selftests/pre_release/tests/cirrusci.py
  selftests/pre_release/tests/vmimage.py.data/variants.yml
  selftests/unit/utils/test_vmimage.py
Labels: LTS release, LTS fix
