Repository avocado-framework/avocado, pull requests merged in 2024-09, with the labels that each got.

#6012 [Doc] Avocado instrumented lifecycle
  docs/source/guides/reference/chapters/avocado_instrumented.rst
  docs/source/guides/reference/index.rst
Labels: documentation

#6010 Tap runner hides failures fix
  avocado/plugins/runners/tap.py
  docs/source/guides/user/chapters/concepts.rst
  docs/source/guides/user/chapters/logging.rst
  selftests/unit/plugin/runners/tap.py
Labels: bug

#6015 Avocado instrumented timeout in setUp and tearDown fix
  avocado/core/test.py
  selftests/check.py
  selftests/functional/basic.py
Labels: bug

#6032 Introduce "exec-runnables-recipe" resolver
  avocado/plugins/list.py
  avocado/plugins/resolvers.py
  avocado/plugins/run.py
  docs/source/guides/writer/chapters/recipes.rst
  examples/nrunner/resolvers/exec_runnables_recipe.sh
  examples/nrunner/resolvers/exec_runnables_recipe_kind.sh
  selftests/.data/whiteboard.py
  selftests/check.py
  selftests/functional/resolver.py
  setup.py
Labels: customer:Passt
