Repository avocado-framework/avocado, pull requests merged in 2025-01, with the labels that each got.

#6086 resultsdb-api support on 3.8 fix
  optional_plugins/resultsdb/setup.py
Labels: bug

#6072 PIP runner introduction
  avocado/plugins/runners/pip.py
  docs/source/guides/user/chapters/dependencies.rst
  examples/nrunner/recipes/runnable/pip_coverage.json
  examples/tests/dependency_pip.py
  python-avocado.spec
  selftests/check.py
  selftests/functional/resolver.py
  selftests/functional/runner_pip.py
  setup.py
Labels: enhancement

#6088 avocado-pre-release pip install
  .github/workflows/prerelease.yml
Labels: bug

#6093 Codecov update
  .github/workflows/push_ci.yml
Labels: refactoring

#6091 Update datatables to 2.2.1 to support advanced searches
  optional_plugins/html/avocado_result_html/templates/avocado_html.js
  optional_plugins/html/avocado_result_html/templates/datatables.bootstrap.js
  optional_plugins/html/avocado_result_html/templates/datatables.css
  optional_plugins/html/avocado_result_html/templates/datatables.min.js
  optional_plugins/html/avocado_result_html/templates/results.html
Labels: enhancement

#6101 PIP dependency in selftests
  selftests/functional/basic.py
Labels: refactoring

#6100 Release plan update
  examples/testplans/release/release.json
Labels: documentation

#6060 Avocado instrumented timeout handling in thread
  avocado/core/test.py
  avocado/plugins/runners/avocado_instrumented.py
  examples/tests/external_logging_stream.py
  selftests/check.py
  selftests/functional/plugin/runners/avocado_instrumented.py
Labels: bug
