Repository avocado-framework/avocado, pull requests merged in 2025-05, with the labels that each got.

#6154 Spawner capabilities
  avocado/core/plugin_interfaces.py
  avocado/core/spawners/common.py
  avocado/plugins/plugins.py
  avocado/plugins/spawners/lxc.py
  avocado/plugins/spawners/podman.py
  avocado/plugins/spawners/process.py
Labels: enhancement

#6157 Set setuptools version to < 80
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: bug

#6158 Utils: document aurl.is_url() actual functionality
  avocado/utils/aurl.py
Labels: Autils
